### ISSUE TITLE
Best practices on Dense representation.

### ISSUE THREAD

**Issue by NitinAggarwal1** [Extreme-classification/ngame#2]
Hi , I am looking to experiment further on the encoders specific for my task . 

I am able to use the models from sentence transformers model by specifying architecture as “STransformers” .

Is there any suggestions from experience about Sentence Transformers vs HF transformers with custom pooling in terms of results quality?

**Comment by kunaldahiya** [comment]
Hi Nitin

Our experience has been pretty good with mean pooling as compared to other standard operations such as CLS token, max etc. However, a custom pooling operator (or cross-attention) can surely lead to gains in some applications - I personally don't have that much experience with it though.
